### ISSUE TITLE
No action upon clicking button "Export presentation"

### ISSUE THREAD

**Issue by sunnyolives** [veggiss/slyderweb#2]
What is supposed to happen? Some more feedback would be nice upon clicking. Browser is Firefox 56.0.2, a name was entered in the adjacent input field and the presentation contained one image of size 1.76 kB and one text element at the time.

**Comment by veggiss** [comment]
When clicking export, a .slyderweb file will start downloading, but it looks like the download method does not call on firefox.

**Comment by sunnyolives** [comment]
Tested in Opera 48.0, Firefox-specific issue confirmed.
